Repository teambition/teambition-sdk, pull requests merged in 2018-11, with the labels that each got.

#571 doc(schemas): 为几个类型添加注释，并引入 UserMe 同等类型 UserSchema
  src/schemas/Message.ts
  src/schemas/UserMe.ts
Labels: Docs

#583 feat(schema): 添加 `unknown` 类型 HomeActivity，支持未知类型的动态
  src/schemas/HomeActivity.ts
Labels: FEATURE, current

#578 fix(schema): 为 TaskDependencySchema 补充带 task 数据的形式
  src/schemas/TaskDependency.ts
Labels: current

#589 fix(schemas): 纠正 TaskSchema `project` 字段为可选字段
  src/schemas/Task.ts
Labels: bug
